project:
  type: website

website:
  title: "Tracy Munene"
  navbar:
    left:
      - href: index.qmd
        text: Home
      
      
      - href: Tracycv.pdf
        text: Resume
        
      - href: project
        text: Projects
  
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

